# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

workflows:
  version: 2
  multi-test:
    jobs:
      # - browser
      - node-v10
      - node-v12

version: 2
jobs:
  node-base: &node-base
    docker:
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - run: node --version
      - run: npm version
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}-{{ .Environment.CIRCLE_JOB }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ .Environment.CIRCLE_JOB }}
      # run tests!
      - run: make unit
      - run: make coveralls
  node-v10:
    <<: *node-base
    docker:
      - image: circleci/node:10
  node-v12:
    <<: *node-base
    docker:
      - image: circleci/node:12
